spring:
  application:
    name: pruebapharoshouse

  datasource:
    url: jdbc:postgresql://localhost:5432/tarjetasservicesdb
    username: postgres
    password: reforma2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    show-sql: true

server:
  port: 8083